### ISSUE TITLE
What environment are you guys using?

### ISSUE THREAD

**Issue by allenwei** [ezmobius/nanite#9]
I met some promblem when using nanite. I think it may caused by gem environment. 
Can you tell me the gem version information which you guys running.

One problem I met is.
After I start up agent and mapper using the simple-agent example which is in the source code, the agent side log stopped at :
[Fri, 06 Nov 2009 17:07:01 +0800] INFO: SEND [register] d72993a0de1aed09f42dd291e5046d3d, services: /simple/echo, /simple/time, /simple/gems, /simple/yielding, /simple/delayed, tags:

And the mapper side the log stopped at:
[Fri, 06 Nov 2009 17:07:11 +0800] INFO: [setup] starting mapper

after a while the mapper down, cause this error
/opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:811:in `connect_server': no connection (RuntimeError)
    from /opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:811:in`reconnect'
    from /opt/local/lib/ruby/gems/1.8/gems/amqp-0.6.0/lib/amqp/client.rb:172:in `reconnect'
    from /opt/local/lib/ruby/gems/1.8/gems/amqp-0.6.0/lib/amqp/client.rb:85:in`call'
    from /opt/local/lib/ruby/gems/1.8/gems/amqp-0.6.0/lib/amqp/client.rb:85:in `unbind'
    from /opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:995:in`call'
    from /opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:995:in `run_deferred_callbacks'
    from /opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:995:in`times'
    from /opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:995:in `run_deferred_callbacks'
    from /opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:242:in`run_machine'
    from /opt/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.8/lib/eventmachine.rb:242:in `run'
    from simpleagent/cli.rb:21

My environment is EventMachine 0.12.8 and amqp 0.6.0, rabbitmq 1.7.1

I just think whether it is rabbitmq permission,I try to re-install rabbitmq and run the "rabbitconf.rb" , then I the problem still.
here is the log when I run "rabbitconf.rb"

Setting permissions for user "mapper" in vhost "/nanite" ...
...done. Setting permissions for user "nanite" in vhost "/nanite" ...
...done. Listing users ...
guest
mapper
nanite
...done. Listing vhosts ...
/ /nanite ...done. Listing permissions in vhost "/nanite" ...
mapper . . .
nanite . . .
...done.

**Comment by roidrage** [comment]
Can you be a bit more specific? Do you mean the installed dependencies of Nanite? Do you get a specific error message at some point while trying it out?

If so, you need either EventMachine 0.12.8 and the amqp gem < 0.6.5 or EventMachine 0.12.10 and the amqp gem = 0.6.5.

**Comment by juanjo** [comment]
I have the same problem than allenwei, even using EventMachine 0.12.10 and AMQP = 0.65

/var/lib/gems/1.8/gems/eventmachine-0.12.10/lib/em/connection.rb:222:in `send_data': eventmachine not initialized: evma_send_data_to_connection (RuntimeError)

My environment:
- Ubuntu 9.10
- Ruby 1.8.7 (2009-06-12 patchlevel 174) [i486-linux]

> $ gem list

**\* LOCAL GEMS ***

actionmailer (2.3.5)
actionpack (2.3.5)
activerecord (2.3.5)
activeresource (2.3.5)
activesupport (2.3.5)
amqp (0.6.5)
eventmachine (0.12.10)
gemcutter (0.5.0)
json (1.2.4)
json_pure (1.2.4)
nanite (0.4.1.15)
rack (1.0.1)
rails (2.3.5)
rake (0.8.7)
rspec (1.3.0)

Any ideas?

Thanks in advance!!!

**Comment by roidrage** [comment]
We're using that stack in production, and the only time we see an error like this is when another exception was raised elsewhere that somehow caused the agent or mapper to die. Could you post some more from the log output and what you're doing, so I can get an idea of what's going on?
